### ISSUE TITLE
Add intention setting

### ISSUE THREAD

**Issue by codegangsta** [codegangsta/Hyperfocus#6]
### `Intention`:

```yaml
name: string
uri: URI
completionURI: URI
completedAt: Time
```

### `Session`:

```yaml
context: Context
start: Time
end: Time
duration: Int
reflection: string
```

### `IntentionLog`:

```yaml
intention: Intention
session: Session
duration: Int
```

### `Context`:

```yaml
name: string
color: string
allowedApps: [string]
allowedURLs: [string]
```

### `ShortcutAction`:
```yaml
name: string
color: string
icon: string
shortcutName: string
stateMask: 'focus' | 'break' | 'idle'
automateOn: 'focus' | 'break' | 'idle'
```
